### ISSUE TITLE
No syndication feed

### ISSUE THREAD

**Issue by da2x** [aidantwoods/aidanwoods.com#1]
I can’t locate an icon or link for the syndication feed, it isn’t found at the common endpoint `/feed`, nor is it discovererable through feed auto-discovery (`<link rel="alternate" type="application/atom+xml" href="https://aidanwoods.com/latest.atom">`).

**Comment by aidantwoods** [comment]
I've pushed [this page](https://www.aidanwoods.com/feed), at https://www.aidanwoods.com/feed and https://www.aidanwoods.com/latest.atom.

Let me know about any feedback you have on what's there – I don't use a reader myself, so not sure as to what the best practices are regarding the optional elements in the spec.

I've followed the syntax specified here: https://validator.w3.org/feed/docs/atom.html

And this seems to think it's okay: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.aidanwoods.com%2Flatest.atom

**Comment by da2x** [comment]
You've got yourself a nice little feed there. 👍 Thanks!

You only need to do is keep writing great posts. Oh, and to include the [auto-discovery mechanism](http://www.intertwingly.net/wiki/pie/AutoDiscovery) on your HTML pages so people (well, their feed readers) will find the feed.

**Comment by aidantwoods** [comment]
Awesome! (and thanks! 😄 )

I've included the auto-discovery now, (just wanted to hold off until I got the okay on formatting).
